import AwardBooks from './award-books';
import PippiStrip from './pippi-strip';
import {BookOpen,MessageCircle,Users,Pencil} from 'lucide-react';
import {ProgramCards,BookFeature,Invitation} from './shared';
export default function Home(){return <><section className="hero wrap"><p className="eyebrow">PICTURE BOOK · HUMANITIES · A BRIGHTER TOMORROW</p><h1><span className="book-mint">그림책</span>으로 꿈을 짓고 <br/><span>인문학</span>으로 삶의 무늬를 만들다</h1><p className="hero-sub">하루 30분, 읽고 질문하고 쓰는 인문학 습관</p><div className="hero-photo"><img src="/images/family-autumn.png" alt="그림책을 함께 읽는 엄마와 두 아이의 이미지"/></div><div className="reading-line">읽기 <i>·</i> 질문 <i>·</i> 쓰기</div></section><section className="wrap section"><ProgramCards/></section><section className="wrap values section"><p className="eyebrow">OUR VALUES</p><h2>아이의 마음이 따뜻하고<br/>단단해지는 이야기</h2><div className="values-grid">{[{Icon:BookOpen,title:'그림책 읽는 마음',desc:'좋은 그림책을 깊이, 천천히 읽으며 마음으로 이해합니다.'},{Icon:MessageCircle,title:'생각을 여는 질문',desc:'스스로 묻고 생각하는 힘을 키워갑니다.'},{Icon:Users,title:'마음을 잇는 대화',desc:'서로의 생각을 존중하며 더 깊은 마음을 만납니다.'},{Icon:Pencil,title:'나를 담는 글쓰기',desc:'오늘의 생각을 글로 남겨 내일의 나를 만납니다.'}].map(({Icon,title,desc})=><div key={title}><Icon size={34} strokeWidth={1.2}/><h3>{title}</h3><p>{desc}</p></div>)}</div></section><BookFeature/><AwardBooks/><PippiStrip/><section className="wrap section about-preview"><img src="/images/director.jpg" alt="대표 박향의"/><div><p className="eyebrow">ABOUT OROTHAN PIPPI</p><h2>함께 읽고, 함께 자라는<br/>우리의 이야기</h2><p>두 딸과 함께 그림책을 읽고 일기를 쓰던 시간이 오롯한 삐삐의 시작이 되었습니다.</p><p>아이와 어른이 자기만의 질문을 발견하고, 삶을 자기 언어로 기록하는 시간을 만듭니다.</p><a className="text-link" href="/about">연구소와 대표 소개 ↗</a></div></section><section className="lecture-band"><div className="wrap"><p className="eyebrow">TOGETHER WITH YOUR COMMUNITY</p><h2><a href="/lectures#lecture-gallery">그림책 한 권으로 열리는<br/>기관 강의와 북토크 ↗</a></h2><p>도서관부터 평생학습센터, 어린이집과 육아종합지원센터까지.<br/>만나는 사람과 공간에 맞는 이야기를 함께 준비합니다.</p><div className="lecture-featured-preview"><a href="/lectures#lecture-gallery"><img src="/images/lecture-03.jpg" alt="함께 듣고 질문하는 북토크 현장" loading="lazy"/></a><a href="/lectures#lecture-gallery"><img src="/images/lecture-07.jpg" alt="참여자들과 이야기를 나누는 기관 강의" loading="lazy"/></a></div><a className="text-link" href="/lectures">강의 현장과 진행 방식 보기 ↗</a></div></section><section className="wrap section" id="stories"><div className="section-heading"><div><p className="eyebrow">OUR STORIES</p><h2>연구소 이야기</h2></div></div><div className="story-grid">{[
  {tag:'NOTICE',title:'새로운 만남을 준비하고 있어요',desc:'프로그램 모집과 연구소 소식은 이곳에서 안내합니다.',image:'새로운 소식',href:'/stories'},
  {tag:'PICTURE BOOK Q&A',title:'그림책 인문학 Q&A',desc:'책 고르기부터 생각을 여는 대화까지, 질문과 답변 6개를 만나 보세요.',image:'그림책 인문학 Q&A',href:'/faq/picture-books'},
  {tag:'DIARY Q&A',title:'일기쓰기 Q&A',desc:'첫 일기부터 꾸준히 쓰는 습관까지, 질문과 답변 6개를 만나 보세요.',image:'일기쓰기 Q&A',href:'/faq/diary'}
].map(({tag,title,desc,image,href},i)=><a className={'story'+(i?' art-only':'')} href={href} key={tag} aria-label={title}><div className={'story-art art-'+i}><span>{image}</span></div>{i===0&&<><p className="eyebrow">{tag}</p><h3>{title}</h3><p>{desc}</p></>}</a>)}</div></section><Invitation/></>}
