import {Invitation} from '../../shared';

export const metadata={title:'눈알 하나로 세상을 다르게 보는 힘 | 그림책 Q',description:'그림책 눈알이 쏙쏙을 통해 관찰력과 상상력, 다르게 해석하는 힘을 키우는 질문을 나눕니다.'};
const images=Array.from({length:13},(_,i)=>`/images/eyes-pop-${String(i+1).padStart(2,'0')}.png`);
const Photo=({n,alt}:{n:number;alt:string})=><figure className="article-insight"><img src={images[n-1]} alt={alt}/></figure>;
export default function Page(){return <><article className="article-page"><header className="article-header wrap"><p className="breadcrumb"><a href="/">홈</a> / <a href="/blog">그림책 Q</a></p><p className="eyebrow">PICTURE BOOK Q</p><h1>눈알 하나로 세상을<br/>다르게 보는 힘</h1><p className="article-intro">같은 물건을 보고도 전혀 다른 것을 떠올리는 아이. 《눈알이 쏙쏙》은 그 엉뚱한 시선이 얼마나 소중한 힘인지 보여줍니다.</p></header><div className="article-body wrap">
<section><Photo n={1} alt="눈알이 쏙쏙과 상상력 이야기"/><h2>아이 눈에 보이는 세상은 하나뿐일까요?</h2><p>그림책 인문학은 아이가 스스로 질문하고 자기만의 답을 찾아가도록 돕는 독서 경험입니다. 이 책은 평범한 사물에 작은 눈을 붙이는 순간 익숙한 세계가 새로운 이야기로 바뀌는 즐거움을 선물합니다.</p><p>정답을 찾는 연습도 필요하지만, 삶에서는 같은 것을 다르게 바라보는 힘이 자주 필요합니다. 아이가 “나는 이렇게 보여”라고 말하는 순간을 존중하면 상상은 생각의 자신감으로 이어집니다.</p><Photo n={2} alt="눈알이 쏙쏙 그림책 표지"/></section>
<section><h2>일상의 물건을 무대로 만드는 타나카 타츠야</h2><p>미니어처 아티스트 타나카 타츠야는 브로콜리를 숲으로, 빵을 구름으로 바꾸듯 가까운 물건의 또 다른 얼굴을 발견합니다. 특별한 재료보다 따뜻한 관찰과 기발한 연결이 먼저입니다.</p><p>책 속 두 눈알 친구가 함께 길을 걷는 다정한 설정 덕분에 아이는 낯선 변신을 편안하게 받아들이고 다음 장면을 먼저 상상해 봅니다.</p><Photo n={3} alt="새롭게 보이는 일상 사물 1"/><Photo n={4} alt="새롭게 보이는 일상 사물 2"/><Photo n={5} alt="새롭게 보이는 일상 사물 3"/></section>
<section><h2>눈알 하나가 깨우는 세 가지 시선</h2><div className="book-notes">{[['01','관찰하는 힘','모양과 색, 방향과 작은 차이를 찬찬히 살펴봅니다.'],['02','상상하는 힘','익숙한 쓰임을 내려놓고 또 무엇이 될 수 있을지 떠올립니다.'],['03','해석하는 힘','다른 답도 존중하며 자기 시선에 이유를 붙여 표현합니다.']].map(([n,t,b])=><div className="book-note" key={n}><span>{n}</span><div><h3>{t}</h3><p>{b}</p></div></div>)}</div><Photo n={6} alt="관찰과 상상을 보여주는 그림책 장면"/><Photo n={7} alt="다르게 보는 세 가지 힘"/></section>
<section><h2>‘미타테’처럼 다르게 본다는 것</h2><p>나무 블록을 자동차라고 부르며 달리던 어린 시절처럼 하나의 사물을 다른 무엇으로 바라보는 발상은 아이에게 자연스럽습니다. 일본 미학의 ‘미타테’도 겉모습 너머의 가능성을 발견하는 시선과 맞닿아 있습니다.</p><p>AI가 많은 답을 빠르게 찾아주는 시대일수록 정해진 공식을 뒤집고 자기만의 연결을 만드는 힘은 더욱 귀합니다. 엉뚱한 생각을 부끄러워하지 않는 아이는 자기 목소리도 당당하게 꺼낼 수 있습니다.</p><Photo n={8} alt="미타테의 시선으로 다시 본 물건"/></section>
<section className="question-box"><p className="eyebrow">QUESTIONS & PLAY</p><h2>아이와 나눌 질문과 상상 놀이</h2><ol><li>이 물건에 눈이 생긴다면 무엇을 보고 싶어 할까?</li><li>같은 물건이 다른 사람에게는 무엇처럼 보일까?</li><li>오늘 가장 새롭게 보였던 것은 무엇이었어?</li></ol><p>“만약에 이것이 ○○라면?”으로 시작하는 릴레이 말놀이도 해보세요. 연필이 마법 지팡이라면, 과자가 비 오는 날의 우산이라면 어떤 일이 벌어질까요?</p><Photo n={9} alt="아이와 함께하는 상상 놀이"/></section>
<section><h2>아이와 이 그림책을 읽어야 하는 이유</h2><p>눈알 하나로 시작한 놀이는 결국 세상을 다르게 보는 큰 질문으로 이어집니다. 책장을 천천히 넘기며 아이가 무엇을 발견하는지 기다려 보세요. 어른이 미처 보지 못한 재미있는 세계를 아이의 말로 만나게 될 것입니다.</p><p>미취학 아동부터 초등 저학년까지 그림만으로도 즐길 수 있고, ‘다르게 보기’에 관한 대화는 초등 전 학년과 나누기 좋습니다. 집 안 물건에 눈알 스티커를 붙이거나 새로운 이름을 지어보는 활동으로도 확장할 수 있습니다.</p><Photo n={10} alt="눈알이 쏙쏙과 상상 활동"/></section>
<section><h2>책에서 시작해 생활로 이어지는 상상</h2><p>책을 덮은 뒤에도 주변 사물을 천천히 바라보세요. 익숙한 컵과 간식, 작은 물건에도 새로운 표정과 이야기가 숨어 있습니다.</p><Photo n={11} alt="눈알이 쏙쏙 그림책과 함께하는 상상력 이야기"/><Photo n={12} alt="자세히 보니 보이지 않던 이야기가 보이는 장면"/><Photo n={13} alt="그림책 속 사물이 새로운 모습으로 변한 장면"/></section>
<section className="activity-panel"><p className="eyebrow">READ & TALK</p><h2>그림책 독후활동지</h2><p>관찰과 상상을 아이의 말로 이어갈 수 있는 질문지를 활용해 보세요.</p><a className="outline-button" href="https://drive.google.com/file/d/1duavlejPu5H6OgShqXA3DUYwZDbcg_Zy/view?usp=drive_link" target="_blank" rel="noreferrer">독후활동지 보기 ↗</a></section><div className="article-back"><a className="text-link" href="/blog">그림책 Q 목록으로 돌아가기 ←</a></div></div></article><Invitation/></>}
