import InstructorCurriculum from '../instructor-curriculum';
import AwardBooks from '../award-books';
import LectureGallery from '../lecture-gallery';
import {socialChannels} from '@/lib/social-channels';
import {notFound} from 'next/navigation';
import {Invitation,ProgramCards} from '../shared';
import ReviewForm from '../review-form';
const data:Record<string,{title:string;tag:string;lead:string}>={about:{title:'오롯한 마음으로, 함께 자라는 곳',tag:'ABOUT US',lead:'그림책 한 권에서 시작한 질문이 아이와 어른의 일상을 바꿉니다. 읽고, 대화하고, 기록하는 배움을 함께합니다.'},children:{title:'초등 그림책 인문학',tag:'CHILDREN',lead:'정답을 찾기보다 자기 생각을 발견하는 시간. 그림책 속 이야기를 나의 삶과 연결하고, 말과 글로 표현합니다.'},'family-workshop':{title:'엄마와 아이, 함께 읽는 시간',tag:'FAMILY WORKSHOP',lead:'같은 페이지를 보며 서로 다른 마음을 만납니다. 가르치는 시간을 잠시 내려놓고, 서로의 이야기에 귀 기울여 보세요.'},instructor:{title:'그림책 인문학 지도사 과정',tag:'INSTRUCTOR COURSE',lead:'그림책을 깊이 읽는 독자에서 배움의 자리를 여는 안내자로. 질문과 대화, 기록을 연결하는 수업을 생각합니다.'},lectures:{title:'기관 강의 · 북토크',tag:'LECTURES & BOOK TALK',lead:'그림책과 일기의 경험을 더 많은 이웃과 나눕니다. 기관의 목적과 참여자의 관심에 맞추어 만남을 준비합니다.'},book:{title:'일기로 배우는 초등 그림책 인문학',tag:'OUR BOOK',lead:'하루 30분, AI 시대를 앞서가는 아이의 인문학 습관. 두 딸과 함께 읽고 써온 일상에서 출발한 책입니다.'},stories:{title:'그림책으로 이어지는 이야기',tag:'OUR STORIES',lead:'연구소의 소식과 수업의 순간, 읽기와 기록에 도움이 되는 자료를 차근차근 전합니다.'},reviews:{title:'함께한 분들의 목소리',tag:'LECTURE REVIEWS',lead:'그림책을 함께 읽고 질문을 나누며 발견한 마음과 배움의 순간을 전합니다.'}};
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;return {title:data[slug]?.title??'페이지를 찾을 수 없습니다'}}
function Cards({items}:{items:[string,string][]}){return <div className="info-cards">{items.map(([title,body])=><div className="info-card" key={title}><h3>{title}</h3><p>{body}</p></div>)}</div>}
function Steps({items}:{items:[string,string][]}){return <div className="steps">{items.map(([title,body])=><div className="step" key={title}><div><h3>{title}</h3><p>{body}</p></div></div>)}</div>}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=data[slug];if(!p)notFound();return <><section className="page-heading"><div className="wrap"><p className="breadcrumb"><a href="/">홈</a> / {p.title}</p><p className="eyebrow">{p.tag}</p><h1>{p.title}</h1><p className="lead">{p.lead}</p></div></section>
{slug==='about'&&<><section className="wrap content-section two-col"><img className="portrait" src="/images/director.jpg" alt="오롯한 삐삐 대표 박향의"/><div className="prose"><p className="eyebrow">DIRECTOR</p><h2>대표 박향의</h2><p>두 딸과 함께 그림책을 읽고 일기를 쓰며, 아이의 생각이 자라고 서로의 마음을 알아가는 시간을 쌓아왔습니다.</p><p>그 경험을 두 딸 김나연, 김다은과 함께 《일기로 배우는 초등 그림책 인문학》에 담았습니다.</p><p>오롯한 삐삐는 초등학생을 위한 그림책 인문학 수업과 성인을 위한 그림책 인문학 지도사 과정을 운영하며, 기관 강의와 북토크로 이야기를 나눕니다.</p><a className="text-link" href="/book">함께 쓴 책 만나기 ↗</a></div></section><section className="wrap content-section"><h2>우리가 생각하는 배움</h2><Cards items={[[ '자기 속도로 읽기','그림과 글 사이에 머물며 각자의 느낌과 생각을 발견합니다.'],['다른 생각에 귀 기울이기','질문을 나누고 서로의 이야기를 들으며 관계를 배웁니다.'],['삶의 언어로 남기기','잘 쓴 문장보다 나의 진솔한 말 한 줄을 소중히 여깁니다.']]}/></section><section className="wrap content-section"><h2>함께하는 활동</h2><ProgramCards/></section></>}
{slug==='children'&&<><section className="wrap content-section"><h2>이런 아이와 함께합니다</h2><Cards items={[[ '초등학생','그림책을 통해 자신과 타인의 마음을 알아가고 싶은 아이'],['생각을 나누고 싶은 아이','질문을 만들고 친구의 다른 생각도 만나고 싶은 아이'],['쓰기를 시작하는 아이','자기 경험과 마음을 말과 짧은 글로 표현하고 싶은 아이']]}/></section><section className="wrap content-section"><h2>읽기에서 기록까지</h2><Steps items={[[ '그림책 만나기','표지와 그림을 살펴보고 이야기를 천천히 읽습니다.'],['나의 질문 만들기','궁금한 장면, 이해되지 않는 마음을 질문으로 꺼냅니다.'],['생각 나누기','정답을 서두르지 않고 서로의 이유를 들어 봅니다.'],['나의 이야기 쓰기','그림이나 한 문장, 짧은 일기로 오늘의 발견을 남깁니다.']]}/></section><section className="wrap content-section two-col"><div><h2>활동 예시</h2><p>주인공에게 편지 쓰기, 기억에 남는 장면 그리기, ‘나라면 어땠을까?’ 질문 만들기, 오늘의 마음을 일기로 남기기.</p><p className="notice">활동은 이해를 돕기 위한 예시입니다. 실제 도서와 내용은 참여 아동의 학년 및 경험에 맞춰 안내합니다.</p></div><div><h2>자주 묻는 질문</h2><details><summary>글쓰기에 익숙하지 않아도 참여할 수 있나요?</summary><p>아이의 읽기·쓰기 경험을 상담 시 알려 주세요. 그림과 말로 표현하는 방식부터 참여 방법을 함께 살펴봅니다.</p></details><details><summary>몇 학년부터 신청할 수 있나요?</summary><p>초등학생을 대상으로 합니다. 학년별 반 구성과 참여 가능 여부는 상담을 통해 확인해 주세요.</p></details><details><summary>수업 일정과 비용은 어떻게 되나요?</summary><p>확정된 모집 정보는 아직 게시되지 않았습니다. 희망 학년과 시간대를 남겨 주시면 상담에 참고합니다.</p></details></div></section></>}
{slug==='family-workshop'&&<><section className="wrap content-section"><img className="family-wide" src="/images/family-autumn.png" alt="함께 그림책을 읽는 가족의 이미지"/></section><section className="wrap content-section two-col"><div><h2>서로를 알아가는<br/>한 권의 그림책</h2><p>엄마의 질문과 아이의 대답이 일방향으로 흐르지 않도록, 서로가 독자이자 이야기의 주인공이 되는 시간을 지향합니다.</p></div><div><h3>참여 대상</h3><p>초등학생 자녀와 함께 그림책 읽기와 대화를 경험하고 싶은 엄마·보호자. 아이의 학년과 참여 인원을 상담 시 알려 주세요.</p><p className="notice">날짜, 장소, 소요 시간과 준비물은 모집 시 별도로 안내합니다.</p></div></section><section className="wrap content-section"><h2>함께 나누는 시간</h2><Steps items={[[ '나란히 읽기','같은 이야기를 각자의 눈으로 읽습니다.'],['서로에게 묻기','내가 고른 장면과 질문을 상대에게 들려줍니다.'],['마음 표현하기','대화와 간단한 기록으로 오늘 알게 된 마음을 남깁니다.'],['일상으로 이어가기','집에서도 함께할 수 있는 읽기와 일기 습관을 생각합니다.']]}/></section></>}
{slug==='instructor'&&<><section className="wrap content-section"><h2>배움의 자리를 열고 싶은 분께</h2><Cards items={[[ '그림책을 사랑하는 성인','그림책을 더 깊이 읽고 인문학적 질문을 나누고 싶은 분'],['교육 활동에 관심 있는 분','아동과 성인의 배움을 돕는 수업을 구상하고 싶은 분'],['독서 모임을 이끄는 분','읽기·대화·기록을 연결하는 활동을 고민하는 분']]}/></section><InstructorCurriculum/><section className="wrap content-section two-col"><div><h2>배운 내용을 이렇게</h2><p>가정에서의 그림책 대화, 독서 모임의 질문 나눔, 교육 현장의 읽기·쓰기 활동 구상에 활용할 수 있습니다. 수료가 취업이나 강사 활동을 보장하지는 않습니다.</p></div><div><h2>모집 안내</h2><p>현재 확정된 모집 일정과 비용은 게시 전입니다. 과정에 대한 관심과 희망 참여 시기를 상담으로 남겨 주세요.</p><p className="notice">자격증 발급 요건과 수료 기준, 시험 관련 세부 안내는 별도로 안내합니다.</p></div></section></>}
{slug==='lectures'&&<><LectureGallery/><section className="wrap content-section"><h2>기관과 함께 정하는 강의 주제</h2><p style={{marginBottom:25}}>아래는 제안 가능한 주제의 예시입니다. 기존 협업 이력을 의미하지 않습니다.</p><Cards items={[[ '도서관 · 평생학습센터','그림책으로 여는 인문학, 질문하는 독자, 일기와 자기 이해'],['어린이집 · 육아종합지원센터','부모와 아이의 그림책 대화, 경청과 공감, 함께 읽는 습관'],['북토크 · 독서 모임','두 딸과 함께한 읽기와 일기, 하루 30분의 기록, 저자와의 대화']]}/></section><section className="wrap content-section"><h2>만남을 준비하는 방법</h2><Steps items={[[ '기관의 이야기 듣기','행사 취지, 참여 대상과 예상 인원을 알려 주세요.'],['내용과 방식 협의','강연, 참여형 워크숍, 북토크 중 목적에 맞는 형태를 살펴봅니다.'],['일정과 조건 확인','희망 날짜, 장소, 소요 시간, 예산과 장비 환경을 협의합니다.'],['출강 확정','세부 내용과 조건을 확인한 뒤 진행 여부를 확정합니다.']]}/><p className="notice">문의 접수만으로 출강이 예약되지는 않습니다. 가능 일정과 진행 조건은 별도 협의합니다.</p></section></>}
{slug==='book'&&<><section className="wrap content-section two-col"><div className="book-cover"><img src="/images/book.jpg" alt="일기로 배우는 초등 그림책 인문학 도서 원본 표지"/></div><div className="prose"><p className="eyebrow">READ · ASK · WRITE</p><h2>하루 30분,<br/>함께 읽고 쓰는 힘</h2><p>박향의 · 김나연 · 김다은 지음</p><p>두 딸과 함께한 그림책 읽기와 일기의 경험을 담았습니다. 매일의 작은 기록으로 아이의 생각과 마음을 만나는 이야기를 전합니다.</p><p>책 표지에 소개된 내용</p><ul><li>27가지 일기 종류에 따른 일기 작성법</li><li>일기쓰기가 달달해지는 엄마의 마음 준비 11가지</li><li>초등 저학년 읽기 독립을 도와주는 그림책·동화책 포함 목록 110권</li></ul><p className="notice">공식 구매처 링크는 확인 후 안내합니다. 도서와 연계한 북토크는 기관 강의 페이지에서 살펴보세요.</p><a className="text-link" href="/lectures">도서와 함께하는 북토크 ↗</a></div></section><section className="wrap content-section"><h2>우리 집에서 시작하는 읽기와 일기</h2><Cards items={[[ '함께 읽기','하루 중 편안한 시간을 골라 그림책 한 권을 펼쳐 보세요.'],['마음 묻기','기억에 남는 장면은 무엇인지, 왜 그런 마음이 들었는지 나눕니다.'],['짧게 남기기','오늘의 생각을 한 줄부터 기록해 보세요. 분량보다 꾸준한 만남이 먼저입니다.']]}/></section></>}
{slug==='stories'&&<><AwardBooks/><section className="wrap content-section"><h2>공지 · 이벤트</h2><div className="empty-note"><h3>새로운 만남을 준비하고 있습니다</h3><p>확정된 모집 일정과 행사 소식이 준비되면 이곳에 안내하겠습니다. 관심 프로그램은 상담을 통해 남겨 주세요.</p><a className="text-link" href="/contact">프로그램 문의하기 ↗</a></div></section><section className="wrap content-section two-col"><div><h2>수업 현장</h2><p>함께 읽고 질문하는 순간들을 차근차근 전해 드리겠습니다. 현장 사진은 참여자의 공개 동의를 확인한 뒤 게시합니다.</p></div><div><h2>읽기 · 기록 자료</h2><p>공개 자료를 준비하고 있습니다. 먼저 출간 도서에서 그림책과 일기를 이어가는 이야기를 만나 보세요.</p><a className="text-link" href="/book">출간 도서 보기 ↗</a></div></section><section className="wrap content-section"><h2>연구소의 다른 공간</h2><p style={{marginBottom:25}}>연구소의 인스타그램·블로그 이야기와 유튜브 채널을 만나 보세요.</p><div className="channel-list">{socialChannels.map(c=><a key={c.type} href={c.href} target="_blank" rel="noopener noreferrer" aria-label={`${c.name} · 새 창에서 열기`}>{c.name} ↗</a>)}</div></section></>}
{slug==='reviews'&&<><section className="wrap content-section two-col"><div className="prose"><p className="eyebrow">VOICES FROM THE CLASS</p><h2>마음에 오래 남는<br/>배움의 순간</h2><p>그림책 한 권을 천천히 읽고 질문을 나누다 보면, 익숙했던 삶을 새롭게 바라보는 순간이 찾아옵니다.</p><p>강의에 참여하셨다면 그날의 생각과 마음을 들려주세요. 후기는 바로 공개되지 않으며, 공개 동의 여부를 확인한 뒤 소개합니다.</p></div><img className="family-wide" src="/images/lecture-03.jpg" alt="그림책과 인문학을 함께 나누는 강의 현장"/></section><section className="review-entry"><div className="wrap content-section review-layout"><aside className="prose"><p className="eyebrow">SHARE YOUR EXPERIENCE</p><h2>강의 후기를<br/>남겨주세요</h2><p>가장 기억에 남은 이야기, 새롭게 발견한 질문, 일상에서 실천해 보고 싶은 내용을 자유롭게 적어주세요.</p><div className="notice"><h3>후기는 어떻게 소개되나요?</h3><p>작성한 후기는 대표가 먼저 확인합니다. 공개에 동의한 후기만 홈페이지에 소개하며, 원하지 않으면 공개하지 않습니다.</p></div></aside><ReviewForm/></div></section><section className="wrap content-section"><h2>강의에서 함께 만나는 경험</h2><Cards items={[[ '그림책을 새롭게 읽는 시간','글과 그림 사이에 머물며 보이지 않던 의미와 내 삶의 질문을 발견합니다.'],['서로의 생각을 듣는 시간','하나의 정답을 서두르지 않고 서로 다른 경험과 관점을 존중하며 나눕니다.'],['일상으로 이어지는 시간','강의에서 얻은 질문을 가정과 수업, 나의 기록 속에서 계속 이어갑니다.']]}/></section></>}
<Invitation program={slug==='children'?'초등 그림책 인문학':slug==='family-workshop'?'엄마와 아이 워크숍':slug==='instructor'?'그림책 인문학 지도사 과정':slug==='lectures'?'기관 강의·북토크':''}/></>}
